### ISSUE TITLE
[Question] How to limite range of sections?

### ISSUE THREAD

**Issue by GustavoFigueira** [antoinebeland/d3-simple-gauge#11]
Hi! I really liked your plugin!

I need the chart like the example below, with the sections with specific range values. It is possible?

![Screenshot_1](https://user-images.githubusercontent.com/15182680/89302162-e2d3be00-d640-11ea-9387-42d7c035044d.png)

Thanks!

**Comment by antoinebeland** [comment]
Hi @GustavoFigueira! 

Thanks for your interest to my plugin. Now, it's not possible to create sections with specific ranges. All the sections are equally divided. However, a parameter could be added in the constructor to specify custom ranges. If you want to create a pull request with the necessary code, you are welcome!
