### ISSUE TITLE
gulp dependency is out of date

### ISSUE THREAD

**Issue by lgodard** [antoinebeland/d3-simple-gauge#13]
`gulp` utilise des paquets qui sont reportés comme problématiques par `npm audit`

```
d3-simple-gauge > gulp > gulp-cli > yargs > yargs-parser 
d3-simple-gauge > gulp > glob-watcher > chokidar >  glob-parent
d3-simple-gauge > gulp > vinyl-fs > glob-stream > glob-parent
```

**Comment by lgodard** [comment]
est ce que le commit https://github.com/antoinebeland/d3-simple-gauge/commit/0c77b38079e9436c817cd324cfe6306e3d02ea49 couvre ce probleme ?

auquel cas, il n'est juste necessaire que de publier une nouvelle version

**Comment by antoinebeland** [comment]
Bonjour @lgodard ,

Il est probable que https://github.com/antoinebeland/d3-simple-gauge/commit/0c77b38079e9436c817cd324cfe6306e3d02ea49 résout le problème. Dans tous les cas, je vais mettre à jour l'ensemble des dépendances du projet, dans les jours qui viennent. Je ferais au même moment un nouveau déploiement sur npm.

Merci pour le signalement de ce problème!

**Comment by antoinebeland** [comment]
Fixed with  https://github.com/antoinebeland/d3-simple-gauge/commit/be61b4e577fa23bbf3088b71195024fc19614947
